// Code generated by github.com/edgedb/edgedb-go/cmd/edgeql-go DO NOT EDIT.

package queries

import (
	"context"
	_ "embed"

	"github.com/edgedb/edgedb-go"
)

//go:embed create_test.edgeql
var createTestCmd string

// createTestResult
// is part of the return type for
// createTest()
type createTestResult struct {
	id edgedb.UUID `edgedb:"id"`
}

// createTest
// runs the query found in
// create_test.edgeql
func createTest(
	ctx context.Context,
	client *edgedb.Client,
) (createTestResult, error) {
	var result createTestResult

	err := client.QuerySingle(
		ctx,
		createTestCmd,
		&result,
	)

	return result, err
}

// createTestJSON
// runs the query found in
// create_test.edgeql
// returning the results as json encoded bytes
func createTestJSON(
	ctx context.Context,
	client *edgedb.Client,
) ([]byte, error) {
	var result []byte

	err := client.QuerySingleJSON(
		ctx,
		createTestCmd,
		&result,
	)
	if err != nil {
		return nil, err
	}

	return result, nil
}
