// Code generated by github.com/edgedb/edgedb-go/cmd/edgeql-go DO NOT EDIT.

package queries

import (
	"context"
	_ "embed"

	"github.com/edgedb/edgedb-go"
)

//go:embed test_query.edgeql
var testQueryCmd string

// testQueryResult
// is part of the return type for
// testQuery()
type testQueryResult struct {
	id     edgedb.UUID               `edgedb:"id"`
	test_2 testQueryResulttest_2Item `edgedb:"test_2"`
}

// testQueryResulttest_2Item
// is part of the return type for
// testQuery()
type testQueryResulttest_2Item struct {
	id edgedb.UUID `edgedb:"id"`
}

// testQuery
// runs the query found in
// test_query.edgeql
func testQuery(
	ctx context.Context,
	client *edgedb.Client,
) ([]testQueryResult, error) {
	var result []testQueryResult

	err := client.Query(
		ctx,
		testQueryCmd,
		&result,
	)

	return result, err
}

// testQueryJSON
// runs the query found in
// test_query.edgeql
// returning the results as json encoded bytes
func testQueryJSON(
	ctx context.Context,
	client *edgedb.Client,
) ([]byte, error) {
	var result []byte

	err := client.QueryJSON(
		ctx,
		testQueryCmd,
		&result,
	)
	if err != nil {
		return nil, err
	}

	return result, nil
}
